version: '3'

services:
  # Nest.js application service
  tier-app:
    image: sanjanivicky/nest-backend:v1 # Specify the Docker image for the Nest.js application
    environment:
      - DATABASE_URL=mongodb://172.30.0.3:27017/studentdb # Use the ip address of mongodb for the MongoDB connection string
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 on the container
    restart: always # Apply the "always" restart policy to ensures that the container restarts automatically if it stops.
    networks:
      app-network:
        ipv4_address: 172.30.0.2 # assign the container a specific ip address within custom network (172.30.0.2)

  # MongoDB service
  tier-db:
    image: bitnami/mongodb:latest # Specify the Docker image for MongoDB
    volumes:
      - app-db:/data/db # Mount a volume for MongoDB data
    ports:
      - "27017:27017" # Map port 27017 on the host to port 27017 on the container
    restart: always # Apply the "always" restart policy
    networks:
      app-network:
        ipv4_address: 172.30.0.3 # assign the container a specific ip address within custom network (172.30.0.3)

# Define a named volume for MongoDB data
volumes:
  app-db:
    # volume that stores MongoDB data, ensuring data persistence

    # Define a custom network with a specific subnet
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 # this ip address is choosen because no network use this ip so that it cannot be overlapping
